### ISSUE TITLE
anyを「すべての」ではなく「いずれかの」にする

### ISSUE THREAD

**Issue by taku0** [t-sin/LLGPL.ja#1]
原文: If any of the functions or classes in the Library are redefined in other files
訳文: もしライブラリの中のすべての関数またはクラスが他のファイル内で再定義されている場合
訳案: もしライブラリの中のいずれかの関数またはクラスが他のファイル内で再定義されている場合
コメント: anyなので「すべての」ではなく「いずれかの」の方が適切です。

**Comment by t-sin** [comment]
コメントいただいた通りだと思います。

単語を一つ換えるのみのため、訳案を使用させていただきます。
