### ISSUE TITLE
Lisp only offers one choice...が抜けている

### ISSUE THREAD

**Issue by taku0** [t-sin/LLGPL.ja#2]
原文: Since Lisp only offers one choice, which is to link the Library into an executable at build time, we declare that, for the purpose applying the LGPL to the Library

訳文: そこでわれわれは、Lispにおいてライブラリを実行可能形式にビルド時にリンクする際にLGPLをライブラリに適用するため、以下のことを宣言します。

訳案: Lispは1つの選択肢、つまりビルド時にライブラリを実行形式へリンクする方法しか提供しません。そこでわれわれは、LGPLをライブラリに適用するため、以下のことを宣言します。
コメント: Lisp only offers one choice...が抜けています。

**Comment by t-sin** [comment]
ここは意味を理解しきれずに訳してしまった部分でした。

訳案を採用させていただいてもよいでしょうか？

**Comment by t-sin** [comment]
一点。

LLGPLはFranz Inc.が著作権を持っているのですが、このリポジトリは許諾なしの翻訳です。そのあたりを確認しないまま翻訳・公開をしてしまったため、一旦同社に問合せをしています。

Franz Inc.からの返答次第によっては、最悪リポジトリを削除することもあります。その際は申し訳ありません。

**Comment by taku0** [comment]
> 訳案を採用させていただいてもよいでしょうか？
はい、問題ありません。
